### ISSUE TITLE
Zerortt test on QNS are failing

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1050]
The reason is simple
the test has change and now it sends a large number of requests using 0RTT and change that a certain amount of bytes has been sent using 0RTT. Our sever sets MAX_STREAMS to 16 which is not enough to send during 0RTT as much as needed by this test.

We need to increase this number.

**Comment by martinthomson** [comment]
This seems wrong.  The test should still pass with a lower limit.  I would open an issue on the interop runner here.  Maybe that means updating documentation for the test so that stream limits and stream data limits are generous enough for the test to pass.  We can update from defaults when we detect the test, but we should have to.
