### ISSUE TITLE
Drop support for drafts -27 and -28

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1153]
The usage rates of these early drafts is low enough that we should remove them.  They are also a tiny bit weaker as they don't do some validation checking (on connection IDs specifically).

This will need to be coordinated with Firefox, probably by removing them from there first (which is just a few lines of code).

**Comment by JaydenElliott** [comment]
Happy to pick this one up @martinthomson as my first issue to tackle! Could I potentially have some guidance on what to do? Would I be removing the occurrences of Draft27/Draft28 in neqo? Also how would I "coordinate it with Firefox"? Thanks

**Comment by ddragana** [comment]
> Happy to pick this one up @martinthomson as my first issue to tackle! Could I potentially have some guidance on what to do? Would I be removing the occurrences of Draft27/Draft28 in neqo? Also how would I "coordinate it with Firefox"? Thanks

Yes, please take the issue. 
You should remove occurrence of draft27/Draft28 and any code that is executed only in case draft27/Draft28 is used.
About Firefox: We also need to remove occurrence of draft27/Draft28. We need to be careful when merging neqo to Firefox and remove draft27/Draft28 from Firefox before that point. You can try to make a Firefox patch as well otherwise someone else will do it, and I will take care that it happens on time.

**Comment by JaydenElliott** [comment]
Just want to confirm that I can delete the invalid_retry() test in the neqo_transport/src/packet/mod.rs file? I believe this is just testing a draft_28 sample retry but I thought I would make sure.

**Comment by JaydenElliott** [comment]
Also, I believe there may be a problem with the linter. 

I am getting an "unused import" build error in neqo_transport/src/connection/mod.rs due to the crate::cid{ConnectionIdRef} import not being used in that file. However, the neqo_transport/src/connection/tests/mod.rs file utilises this import through `use super::{ConnectionIdRef}`. 

Deleting the import in connection/mod.rs, stops the initial build error but causes another build error when attempting to compile the cargo test.

The only solution I have found for this was adding a `#[cfg(test)]` annotation above the import (https://github.com/rust-lang/rust/issues/45268) in the connection/mod.rs file, i.e.
```rust
use crate::cid::{
    ConnectionId, ConnectionIdEntry, ConnectionIdGenerator, ConnectionIdManager,
    ConnectionIdStore, LOCAL_ACTIVE_CID_LIMIT,
};
#[cfg(test)]
use crate::cid::{ConnectionIdRef};

```

Any suggestions on other solutions? This doesn't seem very elegant. @ddragana @martinthomson

**Comment by ddragana** [comment]
Can you update invalid_retry() test to use draft_29 instead of draft_28?

about ConnectionIdRef import: if it is not needed in connection/mod.rs please delete it. o fix he testt buld change 
`use super::{ConnectionIdRef}`
to 
`use crate::cid::ConnectionIdRef;`

**Comment by JaydenElliott** [comment]
I've finished up, all tests are passing except for build_vn();

```
failures:

---- packet::tests::build_vn stdout ----
thread 'packet::tests::build_vn' panicked at 'assertion failed: `(left == right)`
  left: `47`,
 right: `55`', neqo-transport/src/packet/mod.rs:1362:9


failures:
    packet::tests::build_vn
```

I was not able to track down what was going wrong here. Let me know if you have any ideas or if I should send the pull request. Thanks for the help..

**Comment by martinthomson** [comment]
The SAMPLE_VN above that has a list of version numbers encoded into it.  Remove the two versions 0xff, 0x00, 0x00, 0x1b and 0xff, 0x00, 0x00, 0x1c and it should work.

**Comment by ddragana** [comment]
The test verifies a Version Negotiation packet. The packet contains a list of all supported version. SAMPLE_VN contains all version between 27 and 32. In this PR you are going to remove 27 and 28, therefore you need to remove them from SAMPLE_VN. 
Remove bytes 0xff, 0x00, 0x00, 0x1b (draft 27) and  0xff, 0x00, 0x00, 0x1c  (draft 28)

**Comment by JaydenElliott** [comment]
Apologies for this taking so long. I am running into even more test failures and can't seem to figure out what's causing the error. I am happy to fix this next one, I just need some pointers on where to look as I can't pinpoint it.

I am currently getting a test failure in neqo-transport/tests/retry.rs.
The last match statement (line 414) fails because client.state() is not closing and remains "Connected". I threw in some debug statements in the main working branch and my edited branch and in the working code it looks like the connection switches to "Closing" after `assert!(test_fixture::maybe_authenticate(&mut client));`. 

Could somebody point me to the code which is supposed to trigger the Closing so I can look into it (or help with the error). I had a look in the maybe_authenticate() and in the closely proceeding functions and can't find it.

**Comment by martinthomson** [comment]
Thanks for persisting @JaydenElliott.  There are lots of reasons that a connection might close, so it might be easier if you put up a draft pull request with the changes you have and we can try to look into it more.  That's one of the most complicated tests we have and while I thought it should not be affected by this change, it could be any number of things.

**Comment by martinthomson** [comment]
Whoops, forgot to close this.
