### ISSUE TITLE
A timestamp calculation in detect_lost_packets may overflow

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1164]
Please look at this crash:
https://crash-stats.mozilla.org/report/index/4529032a-5770-4f1a-9020-a869f0210616

this [line](https://github.com/mozilla/neqo/blob/49435ab61336ab4d490a2be86c221217b7d4fd5e/neqo-transport/src/recovery.rs#L405) is overflowing.

**Comment by ddragana** [comment]
I still do not know what is going wrong:
`        let lost_deadline = now - loss_delay;`

I don not know whether now or loss_delay is wrong. I will dd a check here before subtracting and also I will add some diagnostic asserts  where loss_delay (and latest_rtt) is calculated.

**Comment by martinthomson** [comment]
How about changing this so that we don't calculate the deadline, but instead change [this line](https://github.com/mozilla/neqo/blob/49435ab61336ab4d490a2be86c221217b7d4fd5e/neqo-transport/src/recovery.rs#L426) to:

```rust
            if packet.time_sent + loss_delay <= now {
```

We don't use `lost_deadline` anywhere else, so the only cost is no precomputation (unless the compiler can optimize for us).
