### ISSUE TITLE
How to change default directory path of neqo-server

### ISSUE THREAD

**Issue by Karthikdasari0423** [mozilla/neqo#1413]
Hi @agrover @pjenvey @jrconlin @martinthomson @hwine 

Thank you all for you contribution.

When i try to download any file using server and client,it is always downloading same below lines
"I am the very model of a modern Major-General,
I've information vegetable, animal, and mineral,
I know the kings of England, and I quote the fights historical
From Marathon to Waterloo, in order categorical;
I'm very well acquainted, too, with matters mathematical,
I understand equations, both the simple and quadratical,
About binomial theorem, I'm teeming with a lot o' news,
With many cheerful facts about the square of the hypotenuse."

any way to change default path to my own directory path where all my files are located ?

am i missing something ,tried --help opetion and -db also but didnt work

Am i missing something

Looking foward for your reply

Thank you,
Karthik

**Comment by jrconlin** [comment]
I'll admit, I'm an admin because I'm one of the last people left in the room, so I can't give a very the best answer.

If I understand what this is supposed to do, this library is demonstrating QUIC using rust. To do so, it builds a `SimpleServer` [that responds](https://github.com/mozilla/neqo/blob/32cf9a7f417cf8d6ca990f55cd023c2b7df0e899/neqo-server/src/main.rs#L412-L420) with that text whenever you make a QUIC request to the SimpleServer. It's therefore a fairly limited library. You might want to look at other, more fully formed HTTP/3 server crates out there.

**Comment by Karthikdasari0423** [comment]
Thank you for replying back.

Okay,will check for any other HTTP/3 server
