### ISSUE TITLE
Neqo server does not discard all the Initial packets that carried in a UDP datagram with a payload size smaller than the minimum allowed maximum datagram size of 1200 bytes.

### ISSUE THREAD

**Issue by KershawChang** [mozilla/neqo#1460]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1851122

**Comment by martinthomson** [comment]
We deliberately didn't implement this, despite the rule existing in the RFC.  Provided that we receive one datagram of the required size, we are OK with creating a connection.

This is safe because we won't create a connection unless we receive one datagram of the required size.  That means that the path supports 1200+ byte datagram payloads, satisfying the requirement that underpins the requirement in the RFC.

Other implementations will apply the rule more strictly and that's OK, but we don't need to.
