### ISSUE TITLE
Neqo server does not close the connection when receiving a packet without any frames.

### ISSUE THREAD

**Issue by valenting** [mozilla/neqo#1476]
(In reply to Kian Kai from comment [bug 1860211 #0](https://bugzilla.mozilla.org/show_bug.cgi?id=1860211#c0))
> Steps to reproduce:
> 
> Packet sequence to replicate the violation:
> 1) Client sends an Initial packet carrying a CRYPTO frame with Client Hello.
> 2) Client sends a Handshake packet without any frames.
> 
> 
> Actual results:
> 
> Violation detail:
> Neqo server does not close the connection immediately after receiving a packet containing no frames.
> 
> 
> Expected results:
> 
> According to Section 12.4, RFC 9000, an endpoint MUST treat receipt of a packet containing no frames as a connection error of type PROTOCOL_VIOLATION. Violations of the protocol lead to an immediate close.

**Comment by martinthomson** [comment]
I'd be more concerned if our client did the same, but I expect that - because they share code - that it will.  We should verify that this only applies to the server.  If it affects the client, then we should fix this.  It's not a super-high priority - servers have lots and lots and lots of ways of wasting browser resources than a few pointless packets - but it's still worth fixing.
