### ISSUE TITLE
Accept Datagrams by reference, not value

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1538]
It looks like `process()` and friends (`process_input()`, `process_path()`, etc..) will work perfectly well with datagram references, so maybe we could change to take those.

For compatibility, we might instead make these take `impl AsRef<Datagram>` instead so that we don't need to change existing uses of the API.

For the multiple inputs, we might change from `Vec<Datagram>` to something like `impl IntoIterator<Item = impl AsRef<Datagram>>`.

**Comment by mxinden** [comment]
> It looks like `process()` and friends (`process_input()`, `process_path()`, etc..) will work perfectly well with datagram references, so maybe we could change to take those.

Agreed that this would be the better API, since most of `process_*` only needs a reference. That said, `save_datagram` requires an owned `Datagram` in order to store it in `Connection`'s  `saved_datagrams`.

https://github.com/mozilla/neqo/blob/28b5c9a669c5f028b425bf96fcb02374c88d454e/neqo-transport/src/connection/mod.rs#L1142-L1152

https://github.com/mozilla/neqo/blob/28b5c9a669c5f028b425bf96fcb02374c88d454e/neqo-transport/src/connection/mod.rs#L251-L255

Is `save_datagram` i.e. partial processing of a datagram, enough of an edge case to warrant a `clone()`?

> For compatibility, we might instead make these take `impl AsRef<Datagram>` instead so that we don't need to change existing uses of the API.

Is `impl AsRef<Datagram>` over `&Datagram` worth it? I see the following problems:

- Adds complexity to the function signatures.
- `AsRef` is not an auto trait, thus requires an additional trait implementation:
    ``` diff
        modified   neqo-common/src/datagram.rs
    @@ -16,6 +16,12 @@ pub struct Datagram {
         d: Vec<u8>,
     }
     
    +impl AsRef<Datagram> for Datagram {
    +    fn as_ref(&self) -> &Self {
    +        self
    +    }
    +}
    +
     impl Datagram {
    ```
- Prevents rustc from inferring the type when providing `None`
    ```
    error[E0283]: type annotations needed
        --> neqo-transport/src/connection/tests/handshake.rs:845:30
         |
    845  |     let out = client.process(None, now());
         |                      ------- ^^^^ cannot infer type of the type parameter `T` declared on the enum `Option`
         |                      |
         |                      required by a bound introduced by this call
         |
         = note: cannot satisfy `_: std::convert::AsRef<neqo_common::Datagram>`
    note: required by a bound in `connection::Connection::process`
        --> neqo-transport/src/connection/mod.rs:1043:50
         |
    1043 |     pub fn process(&mut self, dgram: Option<impl AsRef<Datagram>>, now: Instant) -> Output {
         |                                                  ^^^^^^^^^^^^^^^ required by this bound in `Connection::process`
    help: consider specifying the generic argument
         |
    845  |     let out = client.process(None::<T>, now());
         |                                  +++++
    ```

---

In case it is of some help, here is a pull request using `&Datagram` https://github.com/mozilla/neqo/pull/1543. While adding **a lot** of noise due to updates to the tests, I would argue this is the cleaner API.

**Comment by martinthomson** [comment]
I don't mind the extra complexity or implementing `AsRef` for `Datagram`,  That is, if the ergonomics work out.  How many instances did you need to change?  (A lot.)

As for the type inference problem, most of those uses with `Non` can use `process_output()` on its own instead.
