### ISSUE TITLE
Add support for QUIC Ack Frequency

### ISSUE THREAD

**Issue by jesup** [mozilla/neqo#1656]
https://datatracker.ietf.org/doc/draft-ietf-quic-ack-frequency/

We don't seem to implement it; we seem to have some very partial support for something that preceded it: 
```
// draft-ietf-quic-ack-delay
pub const FRAME_TYPE_ACK_FREQUENCY: FrameType = 0xaf;
```
from frame.rs

There doesn't seem to be a "draft-ietf-quic-ack-delay".

If we do, we may want to be careful about the interaction with congestion control discussed in the draft

**Comment by martinthomson** [comment]
We implement an earlier version of the specification.  I'm supportive of doing this because ACK processing has a significant impact on our performance and if we could get fewer ACKs, we might use that CPU time on other things.  Yes, there is a CC risk, but that is managed with tuning.

It's a relatively straightforward thing to update the implementation, but it's not trivial, so I never found the time for it.

**Comment by larseggert** [comment]
Closing this in favor of #1267.
