### ISSUE TITLE
Getting 0ms callback time

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#177]
Something I notice while looking into firefox logs:
Neqo starts connecting. It sends first packet and set callback to 144ms. After 144ms expires we still do not have a response (rtt was ~170ms), neqo does not have anything to send as well and it returns callback time 0ms. This callback time stays 0ms until we get some packet frow a peer. We are basically busy wait for ~30ms in my case.

**Comment by ddragana** [comment]
There is other situation when we get 0ms callback time. I will need to get some rust logging.

**Comment by martinthomson** [comment]
I have looked at the recovery code in some detail recently and there are a few cases where our timeouts are based on a deadline (as an absolute time).  If we initiate processing, but don't update the underlying conditions that would cause that deadline to be updated, then we will enter this state.

The things we timeout on are:

- ACK delay - if the timer pops, I believe that we always send an ACK; as this ignores CC, I don't think that there is a case where this timer produces zero
- PTO - this should result in a packet being sent always; as with ACK, I don't believe that this should produce a zero timer
- time-based loss recovery - this has the same problem as key updates (below)
- key update timer - I just checked this and there is a case we don't service it; but otherwise this is fine
- idle timeout - if this fires, we should be returning `Output::None` (should this be called `Output::Closed`?)
- pacing - this only applies if we were otherwise going to send a packet AND the pacing time is in the future, so this should never be an issue

From the OP, I don't understand what the 144ms timer is.  Is that the PTO timer?  If it is the PTO timer, we should be sending a packet and reseting the PTO timer.

I found one issue.  If we are Closing, we don't service key update or loss recovery timers.  However, we continue to report them.  So maybe we will thrash if either is waiting on a timer prior to starting shutdown.  That is worth fixing perhaps, but I don't know if that is the source of this issue.

If we are able to construct a test case for the problem, that might be a good thing.

**Comment by ddragana** [comment]
I have seen this a long time ago in firefox. The issue may be fixed already. I will try make a test, but I expect that it is working now.

**Comment by ddragana** [comment]
Did not want to closed it....

**Comment by martinthomson** [comment]
I worked out another case where this goes poorly.

When we are on PTO (in any PN space), and we have exhausted the packet budget we allow, we don't send anything in any PN space.  If our delayed ACK timer has expired, we want to send an ACK, but we can't.  The result is that the delayed acknowledgment timer is set to a time in the past.

Saw this with a Google server that was far enough away to trigger an Initial PTO.  When we get packets from the server, we want to acknowledge them immediately, but as the PTO timer has expired (and we have already sent all the packets), we don't send any packets.  So the delayed ACK timer doesn't get reset.

**Comment by ddragana** [comment]
This was once fixed, we broke it again :)

**Comment by martinthomson** [comment]
With the recent changes, I've added an assertion for this.  So we should close this.

I found one very narrow corner case today where we weren't sending an ACK for a packet number space if we had a PTO in a higher packet number space (e.g., we want to send an ACK for Initial, but Handshake has an expired PTO), but that should be fixed in #618.  Even with that fix, it is theoretically possible for there to be a PTO on Handshake or Initial but we want to send an ACK for ApplicationData and we are unable to send the ACK because the Handshake/Initial packet consumes all space in the packet.  I will open a different issue for that.
