### ISSUE TITLE
Order of events in neqo-transport must be change

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#200]
With the current order of event is the enum NewStream event and some other will be put before StateChange events. We can get  NewStream event before StrateChange(Connected) event. http3 code has some assertions for example that quic transport must be connected if a new stream event is received, etc, therefore this assertion may be hit if the events are in order as above.

**Comment by martinthomson** [comment]
Maybe we should instead use a more specialized event container, or remove any guarantees about ordering.

Right now, I think that we're just relying on the default ordering provided by BTreeSet.  That obviously isn't working to ensure that events pop out in the order they went in.  Even if we did correct the ordering by adding stricter ordering checks on the events, that wouldn't allow us to order NewStream and StateChange events by the way they arrive.

I think that I lean toward simpler code: drop the ordering guarantee and insist that h3 code check the current state rather than rely on getting events to drive its state.

**Comment by agrover** [comment]
@ddragana well the easiest thing to solve your problem is to move `StateChange` to the top in `enum ConnectionEvent` and voila, `StateChange`s come out before `NewStream`s. :smiley: 

No, this needs some serious work. I think there's also an issue where an event like `SendStreamStopSending` should result in an existing `SendStreamWritable` event being discarded. To fix this we need two things: 1) `send_stream_stop_sending()` needs to try to remove events that it supersedes and 2) we need to stop returning multiple events from `events()`, but just return one event at a time. Both of these are doable.

@martinthomson yeah, this is a more specialized event container that I'm advocating, over making upper code check state. BTreeSet let us avoid duplicates but also acts as a priority, so definitely *not* FIFO. (I guess when this was written I was more concerned about dupes, but now it's clear that ordering is the bigger deal.) So we want FIFO, but w/o dupes and some events cull other events. Maybe a `VecDeque`, since there's no FIFO Set type, and then handle culling/dupes ourselves?

Q: If our FIFO collection has a SendStreamWritable and another SendStreamWritable comes in, do we keep the first and drop the second, or vice versa?

**Comment by martinthomson** [comment]
The SendStreamWriteable example might not be a good one because the replacement would be identical to the one it replaces.  For that, it would probably be best to retain the entry at the earliest point that it appeared.  On the other hand, if the event contained a measure of how much data was available, then you might consider keeping only the second.  So maybe it's a good one to talk about ;)

What we could do is have a concept of invalidation that applies to every event.  We'd have to walk the queue in reverse and O(N^2) decide which events invalidated which other events.  For instance, `ZeroRttRejected` probably invalidates a lot of events we've sent already, as does `StateChange(Closed)`.

The other way to manage this is to say that events might be superceded and that we don't remove events that have been rendered invalid by later events.  We would then do what we can to avoid creating duplicates, though this would not be perfect.  For instance, if we sent `SendStreamWriteable`, had flow control credit for that stream used up, then later got more, we might have two `SendStreamWriteable` events sitting there.
