### ISSUE TITLE
Send first Initial multiple times

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#21]
We appear to only send an Initial from the client once.  We should probably try a few times.

**Comment by agrover** [comment]
@martinthomson I'm starting to look at this now. Just to scope the work here:

A new client-specific Connection state called `Connecting` (Or is just State::Init renamed?) which is entered after `handshake()` and `buffer_crypto_records()` are called that sets a timer (maybe 1 second? or 2*initial_rtt or something?)  that if we haven't received a handshake packet from the server we re-send the initial packet. We try 3(ish) times total and if still not in State::Handshaking, we give up and Connection enters a newly added State::ConnectionFailed state.

I'm also looking at Connection::handshake() and thinking maybe we want to break it up into server and client-specific methods, since the flow is already a bit different and seems likely to diverge further.

Thoughts?

**Comment by martinthomson** [comment]
You might want to take a closer look at https://github.com/quicwg/base-drafts/pull/2806.
