### ISSUE TITLE
interop: assertion while connecting to f5

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#231]
we hit assertion at:
https://github.com/mozilla/neqo/blob/85a111e3634cb9f89b1a0bd5496ff9d28a1e218a/neqo-transport/src/send_stream.rs#L348

If I comment out the assertion it is working.

**Comment by martinthomson** [comment]
This seems to be an overzealous assertion, but the fix isn't just to remove it.  We want to make sure that ranges that are retired don't get unmarked.  Retired ranges need to be left alone.

We need a couple of tests for this.  One where the "lost" data is already retired means that we probably need a PTO so that we can send the data twice.

We also need a case where the lost data overlaps with the retired marker.  For instance, when the lost packet contained 0-10 but 0-5 has been retired.  In that case, we want to mark 6-10 for retransmission.

**Comment by agrover** [comment]
I talked to @martinthomson and he has a fix in development for this.

**Comment by agrover** [comment]
fixed by #249
