### ISSUE TITLE
Implement Draining connection state

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#339]
-transport 10.1 talks about distinct closing and draining connection states, which are similar but slightly different. We should look at if we should include Draining as a separate state in our connection state enum, and ensure our draining behavior matches the spec.

**Comment by martinthomson** [comment]
The current code responds to CONNECTION_CLOSE by transitioning to Closed rather than draining.  That's fine-ish, but not ideal.  The ideal code moves to Draining and sends a single CONNECTION_CLOSE.

We probably need a bunch more testing of our closing setup, especially including packet loss in that.

**Comment by martinthomson** [comment]
This has been done!
