### ISSUE TITLE
CC: Define and implement support for "app-limited"

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#350]
@martinthomson says [here](https://github.com/mozilla/neqo/pull/348#discussion_r356387019)

This is tricky, but the basic idea is that you want to avoid congestion control increases if you are unable to send a full congestion window. I don't think that we've settled on this in the spec, so leaving this as a TODO is fine. Make an issue.

Ideas.

We are app limited if:

* there is no application data queued for sending (that's weak, but it might be enough)
* bytes_in_flight never reached cwnd in the last RTT (that might be too strong and cause us to never increase, particularly when you consider pacing, so you might have to pad the time or reduce the target somehow)

Ian had a few other ideas, but they are all hard to execute. Defer this. False is a fine starting position.

**Comment by ddragana** [comment]
I think we need to fix this soon. We are a client side so that is not a big problem, but it is going to have bad effect on throughput.
I think the trigger should be:  we want to send a packet(in case of pacing) but we do not have data to send. For non pacing case: we can send more packets (bytes_in_flight is less than cwnd) but we do not have data to send.

**Comment by martinthomson** [comment]
The check here will only ever reduce throughput.  The intent is to reduce throughput when the full capacity of the link isn't being realized on the basis that increases to the window might overestimate available capacity.

The pacing idea seems approximately right, but it might not work because we might not be executing at that point.  That is, if the last packet was full, we might not schedule a timer for the pacing interval and instead let the connection go idle.  I guess that we can detect that gap when the ACK comes in and we try to increase the CWND.

**Comment by ddragana** [comment]
this is dup of #276 ?

**Comment by ddragana** [comment]
I am working on this.
