### ISSUE TITLE
Use constants in loss recovery tests

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#46]
There are lots of constants here, like `Duration::from_micros(94_609)`.  The test would be far more readable with constants.  Separating this into T1, T2, or STEP1, STEP2 and so forth would help a lot.

_Originally posted by @martinthomson in https://github.com/mozilla/neqo/pull/39_

**Comment by NorahKiggundu** [comment]
Hey,
I would like to fix this. It is my first time working on open source code. Please guide me on how to fix this.

**Comment by agrover** [comment]
@NorahKiggundu hi! It looks like @martinthomson already fixed this, with 9c8b3eb854bf44c66c71c1b778ef99a5c725477a. (At least, I don't see any of the super bad tests in the current code any more.) 

Thanks for your attention to this issue. I'm going to close this one since it is complete, but I'm sure we have some other issues that might be good places to start. Thanks again.
