### ISSUE TITLE
Remember RTT from previous connection

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#479]
We can use this to seed the RTT.

**Comment by ddragana** [comment]
@martinthomson, can you explain it a bit more. I assume you are thinking to store rtt in resumption token?

**Comment by martinthomson** [comment]
Yes.  That was the idea.  Store it alongside other information and use it as the initial RTT estimate (maybe only if the source and destination IP are ~the same).

**Comment by ddragana** [comment]
In this lines:
https://github.com/mozilla/neqo/blob/master/neqo-transport/src/connection.rs#L506-L515

we encode "transport parameters" and a token. Rtt needs to be added.

In this function we decode them:
https://github.com/mozilla/neqo/blob/master/neqo-transport/src/connection.rs#L529

Rtt is part of [LossRecovery](https://github.com/mozilla/neqo/blob/master/neqo-transport/src/recovery.rs#L273)
We need to remember a smoothed [RTT](https://github.com/mozilla/neqo/blob/master/neqo-transport/src/recovery.rs#L43)

After resumption we will set it as a initial RTT.

**Comment by surender786** [comment]
I am Outreachy May 2020, Can you assign me on it.
it is my first contribution.

**Comment by surender786** [comment]
Hi Ddragana thanks for assigning me.
Now tell me How i can fix this issue.I am new here.

**Comment by ddragana** [comment]
Look at comment above:
https://github.com/mozilla/neqo/issues/479#issuecomment-596528272

Take a look a functions I linked to. Please ask if you have any questions.

**Comment by surender786** [comment]
Ok Mentor... 
I will see it and contact you very soon.

**Comment by surender786** [comment]
> Look at comment above:
> [#479 (comment)](https://github.com/mozilla/neqo/issues/479#issuecomment-596528272)
> 
> Take a look a functions I linked to. Please ask if you have any questions.

hey...please explain in detail ....
how i fix it???

**Comment by ddragana** [comment]
I this code:
https://github.com/mozilla/neqo/blob/master/neqo-transport/src/connection.rs#L506-L515

we serialize a lot of information into a Vec<u8>. You will need to serialize rtt as well. We have a helper structure Encoder to do that. The Encoder is defined [here](https://github.com/mozilla/neqo/blob/c07519cacbede063048b159ed65117e26f719acf/neqo-common/src/codec.rs#L188). It has a function `encode_uint` that can serialize a integer and you can use it to serialize a smoothed_rtt value. 
[smoothed_rtt](https://github.com/mozilla/neqo/blob/master/neqo-transport/src/recovery.rs#L43) is of type Duration but you can transform it in milliseconds and store milliseconds. smoothed_rtt is  private so you will need to create a getter function to expose it. 

Similar, neqo_common::Decoder has a appropriate decode_uint function that you can use to deserialize  smoothed_rtt. And you will need setter function to set the value in RttVals.


Testing:
Some explanation:
are you familiar with networking? Do you know what is RTT?
So rtt is "round trip time" how long it takes a packet to from one side of a connection to other side and back.
Our test code uses now() to get a time stamp. You can advance time by:
```
let mut now = now();
now += Duration::from_millis(100);
... do something that uses 'now'
now += Duration::from_millis(100);
... do something that uses 'now'
```
struct Connection has a function with name '[process](https://github.com/mozilla/neqo/blob/master/neqo-transport/src/connection.rs#L747)' that it the function that takes a QUIC packet and reads it. It also takes parameter 'now' and that is time when the packet has arrived. The function also produces a packet.

Here is a test that uses a resumption token:
https://github.com/mozilla/neqo/blob/master/neqo-transport/src/connection.rs#L2560
You will need the same test just you will need to check that after a resumption rtt is set.
In this [line](https://github.com/mozilla/neqo/blob/master/neqo-transport/src/connection.rs#L2565) we connect a client and a server.
in this [line](https://github.com/mozilla/neqo/blob/master/neqo-transport/src/connection.rs#L2567), a resumption token is set.
The lines after that we create a new client, then set the token we got couple a lines above. As soon as we set a token we should have smoothed_rtt of the 'client' the same as on tthe previous connection. You can make a function getter function for smoothed_rtt that is only existing for tests('#[cfg(test)]')

This tests will return smoothed_rtt == 0 because the time is not really passing. to emulate that you will need to make time pass with `now += Duration::from_millis(100);`
The test uses connect() function that uses handshake() function that calls process. The handshake function uses now() and you need to emulate that time is passing as explained above.
