### ISSUE TITLE
Document build process on Linux

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#495]
This should include:
- [x] Suggested Ubuntu OS version to use and how to install required deps 
- [ ] Suggested Fedora (or CentOS) version to use and how to install required deps

**Comment by mahakbansal2019** [comment]
Hey @agrover 
I would like to work on this .
Could you please elaborate this more .
Thank you :)

**Comment by agrover** [comment]
@mahakbansal2019 we just need somebody to write some step-by-step instructions on how to get Neqo building on one (and preferably two) Linux variants, starting from a fresh OS install. Probably we want it in Markdown format, but starting with just a plain text file would also be fine I think. Hope you can help us out :smiley:

**Comment by mahakbansal2019** [comment]
@agrover  There are no official docs available for building neqo 
so how should I proceed further?

**Comment by agrover** [comment]
Are you using Ubuntu or Debian? If so, one spot where this info is is actually in our docker/Dockerfile, but as a series of build instructions rather than docs. That might be a place to start.

**Comment by mahakbansal2019** [comment]
I’m using ubuntu and one more thing to ask 
Do I need to write detailed instructions of the process of building neqo

**Comment by agrover** [comment]
Yes that's the task.

**Comment by mahakbansal2019** [comment]
Okay 
Thanks for the clearity @agrover 
I’ll surely work on this.

**Comment by mahakbansal2019** [comment]
@agrover Am I going correct or I need to change my way of writing?
OS Version : 18.04

**How to install neqo in the respective version :**
In Order to build neqo, you need the following support libraries and tools"
	

1. Latest released version of Clang & LLVM
2. Development files for LLVM & Clang + their transitive dependencies(e.g. libclang-dev, zlib1g-dev)
3. GNU make or ninja	
4. pkg-config

**RUN:**

-  `sudo apt-get update && apt-get install -y --no-install-recommends`

apt-get update downloads the package lists from the repositories and updates them to get information on the newest versions of package and their dependencies . It will do this for all repositories and PPAs.To avoid installing recommended packages either use --no-install-recommends option with apt-get 

- `ca-certificates coreutils curl git make mercurial ssh \`

- To clear unnecessary things from your local repo 

- `apt-get autoremove -y && apt-get clean -y`

The main difference btw apt-get autoremove and apt-get clean is that autoremove uninsatll software that hasn't been installed manually by the user and that's not needed by any other software.
while auto-get clean does something else when we use apt to install or update something from a repository , it first downloads all the needed packages to your devices and then installs them .apt-get clean removes those downloaded packages and it doesnot uninstall any software it just cleans that cache.

- ` rm -rf /var/lib/apt/lists/*`

Set up the environment using this:
```
RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=1.41.1
```

**Comment by agrover** [comment]
Ubuntu docs added in #719

**Comment by larseggert** [comment]
Nice to have, but would need to be maintained by someone. I'm not even positive the Ubuntu docs are accurate anymore.

(It's not really in the most readable form, but the CI `check.yml` builds for Ubuntu and hence works.)
