### ISSUE TITLE
CircleCI is intermittently failing

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#758]
https://app.circleci.com/pipelines/github/mozilla/neqo/2006/workflows/2cd21713-458b-42df-aca8-a8ae483a61d2/jobs/2006/steps

Looks like some sort of memory exhaustion issue :disappointed:

**Comment by agrover** [comment]
@martinthomson do you have any ideas for what we should do here?

**Comment by martinthomson** [comment]
As of now, I'm not sure.  I think that the long-term goal would be to move to taskcluster so that we can get better support overall.  Having looked at that a little yesterday, it's a proper project.

I've been playing around with GitHub Actions and that might be different, but I'm not entirely sure if it would fix the problem.  It's a little more flexible and maybe we can sort out the dockerhub problem by building images as part of that.  Still, that's non-zero work as well.

**Comment by martinthomson** [comment]
https://stackoverflow.com/a/57817848/1375574 might help us in the short term.  Installing and using lld seems like it would be a net gain.

**Comment by martinthomson** [comment]
Looks like the docker image change is good.  We'll see if the switch to lld sticks.

**Comment by martinthomson** [comment]
Happy to report that this seems to be working.
