### ISSUE TITLE
Clarify relationship to Quinn

### ISSUE THREAD

**Issue by jeffparsons** [mozilla/neqo#81]
Hi there! 👋

How does this project relate to [Quinn](https://github.com/djc/quinn)? I think it would be worth clarifying this in a "related/similar projects" section in the README, because the two projects appear on the surface to have very similar goals.

More detailed questions that immediately jump to mind when trying to understand which I should be interested in:

- What is the scope of each project? Is it exactly the same, or are they tackling different parts of the problem? E.g. is one only a state machine for the protocol, rather than a "batteries included" server/client library?
- Are their approaches mutually incompatible in some way that might steer me toward one or the other depending on my use case?
    - Does one have a specific use case (e.g. integration into an existing code base) that dictates particular details of its interface that might not be desirable outside of that code base?
- Can they be used together? Is there some component that is common to both? Could there be in future, or should the code remain deliberately unrelated?

I have nothing against there being multiple QUIC projects in the Rust ecosystem (diversity is great when there's a reason for it!), but when they appear at least superficially to have essentially the same purpose, it seems like it would be helpful to clarify somewhere prominent why each exists, what the tradeoffs are, etc.

Thanks! 😊

**Comment by martinthomson** [comment]
@jeffparsons, these are two projects that happen to be implementing the same protocol in the same language.  I'm not sure that this requires special justification, but I will provide you with some context.

Mozilla have been involved with QUIC since very early in the project and we have always intended to build our own stack. There are a bunch of boring technical reasons, but the overarching reason is that we think that it is important to have tight control over this part of our code, as it is important to our strategy.

**Comment by jeffparsons** [comment]
Fair enough. Thanks for the explanation! :)

**Comment by dzmitry-lahoda** [comment]
given neqo depends on quinn-udp now, is there future plan to deepen integration?  use more of quinn?

**Comment by martinthomson** [comment]
There are no such plans.  As always, if there is a component where it makes sense to collaborate, we will, but we have no plans to do that.
